<?php
// Minimal bootstrap placeholder - in a real Laravel app this is generated by framework bootstrap

// This file is a placeholder to make artisan script reference work for demos.

require_once __DIR__.'/../vendor/autoload.php';

$app = new Illuminate\Foundation\Application(
    dirname(__DIR__)
);

return $app;
